name: Tests
on: [push, pull_request]

jobs:
    tests:
        strategy:
            matrix:
                php: [8.0, 7.4, 7.3, 7.2, 7.1]
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   run: composer tests
